### ISSUE TITLE
Add support for Concerns

### ISSUE THREAD

**Issue by vietqhoang** [theodorton/yard-activerecord#18]
A lot of my ActiveRecord models share functionalities with Concerns. The docs do output that the Concerns are included, but the includes do not get generated. Would be great to see the plugin expanded to support this.

**Comment by olance** [comment]
To all people needing this as I myself did, I just released a gem to handle those concerns!

https://github.com/digitalcuisine/yard-activesupport-concern

**Comment by theodorton** [comment]
Great work, @olance! Is this plugin compatible with `yard-activerecord` - will `parse_block` pass of handling the `has_many` etc. to `yard-activerecord`?

**Comment by olance** [comment]
Thanks ^^

Yes it should, as what my plugin does is simply telling YARD to parse the `included`/`class_methods` blocks and attach generated doc to the current namespace. There's no assumption as to what contain those blocks, so any custom handler should be triggered :)

**Comment by peteryates** [comment]
Excellent, this works perfectly for me. Thank you @olance

**Comment by olance** [comment]
You're welcome! :)
