### ISSUE TITLE
Deprecate in favor of annotate gem

### ISSUE THREAD

**Issue by goatandsheep** [theodorton/yard-activerecord#31]
The [annotate gem](https://github.com/ctran/annotate_models) seems to be actively supported. Should we deprecate this in favor of annotate?

**Comment by theodorton** [comment]
I think annotate and yard-activerecord serve somewhat different purposes. If there are things you'd like to see added to the project or you're experiencing issues using it, I welcome that feedback.

**Comment by goatandsheep** [comment]
It's ok. You rock @theodorton . I hadn't seen commits in a while so I figured it might be easier to suggest to deprecate. Great stuff with the updates!
